version: 0.0
os: linux
files:
  - source: /new
    destination: /home/ec2-user/

hooks:
  AfterInstall:
    - location: /bin/bash
      timeout: 300
      runas: ec2-user
      script: |
        GITHUB_REPO="nagarajcap/Javaupgrade21"  # Replace with your GitHub repo
        GITHUB_TOKEN="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"       # GitHub token with repo access
        GITHUB_WORKFLOW="jmeterui.yml"      # Replace with the exact workflow filename
        REF="master"                             # Branch reference to trigger the action

        # Trigger GitHub Action via GitHub API
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/$GITHUB_REPO/actions/workflows/$GITHUB_WORKFLOW/dispatches \
          -d '{"ref":"'"$REF"'"}'
