name: Hello World Action

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: echo "Hello, ${{ github.event.inputs.name }}!"
