name: Hello World Action

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: self-hosted

    steps:
    - name: Print Hello World
      run: echo "Hello, World!"

    - name: Performancce test
      run: jmeter -n -t .\SampleAPI.jmx -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l .\SampleAPIjtl.jtl

